### ISSUE TITLE
Where do I list my project?

### ISSUE THREAD

**Issue by Hetarth02** [MunGell/awesome-for-beginners#1023]
Basically, I have a json file in which data is to be added. So, it would be helpful if someone would guide me in choosing the right category to list my project?
I am currently considering to list my project under the `markdown` category.

**Comment by MunGell** [comment]
Hi @Hetarth02 

I am not sure I fully understand what your project is about.
Could you please share the link to it so that I can provide meaningful suggestion as to where it would fit best?

**Comment by Hetarth02** [comment]
Hello @MunGell 
In a nutshell, I am trying to create a website where one can get digestible and intuitive definitions of complex concepts.

**Comment by MunGell** [comment]
Hi @Hetarth02 

Sorry for the delay. Can you share link to your project repository?

**Comment by sammyhori** [comment]
Closed as stale
