### ISSUE TITLE
The label for godot engine is wrong

### ISSUE THREAD

**Issue by whatthesamuel** [MunGell/awesome-for-beginners#1039]
shouldn't the label for godot engine be "good first issue" instead of "junior job"? there are no results labeled as junior job in the godot issues.

junior job label = https://github.com/godotengine/godot/labels/junior%20job
good first issue = https://github.com/godotengine/godot/labels/good%20first%20issue

**Comment by bhattabhi013** [comment]
Hii
Can you assign this issue to me?

**Comment by bhattabhi013** [comment]
I've fixed the mentioned issue and generated a PR. #1042
