### ISSUE TITLE
Adding more beginner friendly C# projects 

### ISSUE THREAD

**Issue by mohakdev** [MunGell/awesome-for-beginners#1068]
Hey, I noticed there are very few `C#` Language Beginner friendly projects. I know some more projects which are perfect for newcomers so can I add those to the list and make a PR?

Some of the projects I want to add are
- [Files](https://github.com/files-community/Files) 
- [mono](https://github.com/mono/mono)

and some others

**Comment by UTKARSH8768** [comment]
hey i am utkarsh sharma can you please assign me a task to contribute in your project. This is for my open source project lab in my college .Contact me at my mail id sharmautkarsh19@siesgst.ac.in

**Comment by NotSooShariff** [comment]
Hey, can you please assign me a task to contribute? I would love to add some beginner-friendly projects in c#.

**Comment by shyambaral** [comment]
hey can you assign this code to me
