### ISSUE TITLE
Outdated repositories may need to be removed

### ISSUE THREAD

**Issue by Asantae** [MunGell/awesome-for-beginners#1069]
Some of the repositories listed have all of the beginner-friendly issues closed. I noticed in the contributing.MD notes some guidelines for open-source repos to this list but was wondering if some guidelines should be added for removing things as well.

**Comment by Asantae** [comment]
I should have noted before that I am specifically referring to the Javascript section in the README.md by the way

**Comment by T-Wesst** [comment]
Hi @Asantae is this currently being worked on? I would love to contribute.
Just to clarify, you want to remove only the repositories labeled "beginner-friendly" where the issues are closed?

Additionally, what sort of guidelines did you have in mind regarding removing repos?

**Comment by Asantae** [comment]
I worked on the javascript section and just did a pull request for it, but only that section. there are a ton of other sections with outdated or inactive links/repos. Would be great if you could work on those

**Comment by T-Wesst** [comment]
Is this related to #1011 ? If so I have a WIP GitHub Action than runs a Python script. The script reads the README.md file and writes all of the urls into a text file for later use.

**Comment by Asantae** [comment]
I actually didn't notice #1011, my apologies. But with that being said I was also including outdated repos/dead links and corrected a few typos. I was also wondering if the py script accounted for other first-timer friendly tags like "beginner-friendly", "difficulty-easy", "first-timers-welcomed" etc

**Comment by T-Wesst** [comment]
I'm not able to push my branch up so I'll probably have to fork. I'm trying to get the to correctly filter for all edge cases.
For the most part, I've captured all github and gitlab links but I'm not sure if the filter should only capture "beginner-friendly" or a catch all solution?

I'm having a bit of trouble setting a stop flag at the end of the url
As of right now I'm getting outputs like so:

![Screen Shot 2022-06-04 at 11 15 06 AM](https://user-images.githubusercontent.com/34630856/172020317-6a4b8bc7-0883-4f69-9032-dfa550cefdf6.png)

with this regex
`regex = 'http[s]?:\/\/(?:github|gitlab).com\/[a-zA-Z].+\/.+\/[a-zA-Z]'`

**Comment by MunGell** [comment]
Hi @Asantae @T-Wesst 

Thank you for your work, I've incorporated it into the repository now!
