### ISSUE TITLE
broken link url to CONTRIBUTING.md in github action 

### ISSUE THREAD

**Issue by ntedgi** [MunGell/awesome-for-beginners#1104]
![Screen Shot 2022-09-13 at 10 41 59](https://user-images.githubusercontent.com/31243793/189841755-829d0071-9557-4345-9269-65960e48d041.png)

this link not working and lead to :
https://github.com/MunGell/awesome-for-beginners/CONTRIBUTING.md
![Screen Shot 2022-09-13 at 10 45 50](https://user-images.githubusercontent.com/31243793/189841934-ae4318bf-ad06-439b-aecc-6649fb4ae7a9.png)

**Comment by NitinRana-code** [comment]
This link is wrong https://github.com/MunGell/awesome-for-beginners/CONTRIBUTING.md

Right link is https://github.com/MunGell/awesome-for-beginners/blob/main/CONTRIBUTING.md

**Comment by ntedgi** [comment]
You right need to update github action as well

**Comment by NitinRana-code** [comment]
sorry but it is my time i don't know how to do that can you teach me how to update action please

**Comment by ntedgi** [comment]
Fork this project
Go to .github/
Edit the right action
Commit
Push
Open PR

**Comment by MunGell** [comment]
Thanks for the fix!
