### ISSUE TITLE
non-code category

### ISSUE THREAD

**Issue by noraj** [MunGell/awesome-for-beginners#1127]
Hi,

I have a website that is an Inventory of Cybersecurity tools and resources (https://inventory.raw.pm/).

Of course there are a few opportunities for Pug, Javascript/Jquery, but most of the beginer friendly issues are just adding data in JSON.

https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/issues/?label_name%5B%5D=difficulty%3A%3Aeasy

- https://inventory.raw.pm/contribute.html
- https://inventory.raw.pm/docs/add

So is there a way to create a non-code category?

**Comment by keshav-rockwinder** [comment]
can you please elaborate your problem? and request this issue to me
?

**Comment by noraj** [comment]
The project sort projects by languages

![image](https://user-images.githubusercontent.com/16578570/193424621-47fe5e46-55cb-418a-ac04-da0e29cb2877.png)

same in https://github.com/MunGell/awesome-for-beginners/blob/main/data.json

but my project is a website, there is not much code to contribute to but rather adding data as JSON, 99% of the contributions are not code. But I guess it could be the same for the project that are only documentation and where people just write markdown.

So I was asking if it was possible to a non-code category for those kind of project that requires contributions that are not code.

**Comment by SuryanshSinha2612** [comment]
I am submitting a pull request please accept it

**Comment by Gun2902** [comment]
i want to contribute in this project

**Comment by GuyEternal** [comment]
I think there is a way to create a non-code category named json? @noraj

**Comment by abhinav17apr** [comment]
i want to contribute in this

**Comment by PrathameshTheurkar** [comment]
I would like to contribute in this project.

**Comment by abhi87374** [comment]
I WANT TO CONTRIBUTE

**Comment by Rajeevjewar** [comment]
I want to contribute to this project

**Comment by sammyhori** [comment]
When adding entries to the `data.json`, the `technologies` list does not have a fixed set of possible values.

This means you can add `json` to this list and it should just make a new category for it, if it doesn't already exist.
