### ISSUE TITLE
Yarn's label for beginner issues is now `good-first-contribution`

### ISSUE THREAD

**Issue by bradarv90** [MunGell/awesome-for-beginners#113]
Change label for yarn from `label:"good first bug" ` to `label:good-first-contribution`

**Comment by MunGell** [comment]
Hi @bradarv90 

Thank you for flagging this issue.
I am going to make it an issue for new contributors to fix.

What needs to be done:
1. Label for Yarn project needs to be changed to `good-first-contribution`
2. Link for Yarn project needs to be changed to `https://github.com/yarnpkg/yarn/labels/good-first-contribution`

Thanks
