### ISSUE TITLE
Add qwik.js in Js

### ISSUE THREAD

**Issue by Rohitchaudhary13** [MunGell/awesome-for-beginners#1191]
Let's add another famous framework. Qwik offers the fastest possible page load times - regardless of the complexity of your website. Qwik is so fast because it allows fully interactive sites to load with almost no JavaScript and pick up from where the server left off
. As users interact with the site, only the necessary parts of the site load on demand. This precision lazy-loading is what makes Qwik so quick.

**Comment by Dhanunjay18** [comment]
Hello i want to add hacktoberfest label to it @Rohitchaudhary13
