### ISSUE TITLE
Ansible in this list

### ISSUE THREAD

**Issue by TechWiz-3** [MunGell/awesome-for-beginners#1205]
Simple question: how on earth is Ansible a good project to contribute to for beginners??

**Comment by Auti29** [comment]
Ansible is a software tool that enables cross-platform automation and orchestration at scale and has become over the years the standard choice among enterprise automation solutions.

**Comment by TechWiz-3** [comment]
Like you said they're a huge project, how could contributing such a massive project be beginner friendly?

**Comment by sammyhori** [comment]
Closed as stale.
