### ISSUE TITLE
Can i add an awsome place for beginner's

### ISSUE THREAD

**Issue by Logan1x** [MunGell/awesome-for-beginners#122]
@MunGell  actually i am a new to open source world and i find out that an github repo and slack group by [open-source help community](https://github.com/OpenSourceHelpCommunity) so if you grant permission i add pr. what do you think let me know!!

**Comment by PeriGK** [comment]
I believe if you follow the guidelines that are shown here, the guys will be fine and you dont need any permission.

https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md

**Comment by Logan1x** [comment]
@PeriGK  actually it's org not repo so that why asking

**Comment by MunGell** [comment]
Hey @Logan1x 

Not sure I am following what you are asking for.

@PeriGK is right, you don't need any special permission to create a PR in this repository.

**Comment by Logan1x** [comment]
Hey @mungell I know i don't need permission but please have a look at link in previous comments, its an repo not an module/library.

**Comment by MunGell** [comment]
Sorry, I don't know how to help here.
