### ISSUE TITLE
Invalid OpenRA reference

### ISSUE THREAD

**Issue by Kissaki** [MunGell/awesome-for-beginners#1226]
> OpenRA (label: Easy)

OpenRA [has no such label ‘Easy’](https://github.com/OpenRA/OpenRA/labels?q=Easy). I see no equivalent label either.

**Comment by sammyhori** [comment]
Looking through their labels now, they still have no goodfirstissue or equivalent tag for issues.
I suggest they are removed from the list.

**Comment by ChristophTempelhoff** [comment]
They should definitely be removed as they apparently do not fit the criteria anymore

**Comment by sammyhori** [comment]
Closed by #1478
