### ISSUE TITLE
Webpack no longer has `easy` label.

### ISSUE THREAD

**Issue by nbkhope** [MunGell/awesome-for-beginners#125]
Instead, it has the following applicable ones:

* [D0: My First Commit (Contrib. Difficulty)](https://github.com/webpack/webpack/labels/D0%3A%20My%20First%20Commit%20%28Contrib.%20Difficulty%29)
* [D1: Easy (Contrib. Difficulty)](https://github.com/webpack/webpack/labels/D1%3A%20Easy%20%28Contrib.%20Difficulty%29)

**Comment by MunGell** [comment]
Thank you for the info!
