### ISSUE TITLE
CDNJS repository is robot-only

### ISSUE THREAD

**Issue by sleeepstorm** [MunGell/awesome-for-beginners#1254]
As one of the C# repositories, *cdnjs* is a "robot-only" repository so it doesn't accept pr's anymore.

I recommend that you remove it from the list.

**Comment by Darshantawte** [comment]
Hello , i am ready to work on this can you please help in relocating where the list is ?

**Comment by nikhilhex** [comment]
CDNJS is a JavaScript repository so you can find it in the JavaScript section.

**Comment by roy9495** [comment]
The "human" repository for cdnjs is cdnjs/packages. The "robot" repository for cdnjs is cdnjs/cdnjs . Should we update it or remove it from the list?

**Comment by nikhilhex** [comment]
> The "human" repository for cdnjs is cdnjs/packages. The "robot" repository for cdnjs is cdnjs/cdnjs . Should we update it or remove it from the list?

I think changing it to the "human" repository would be ice since
that is an open-source opportunity after all.

**Comment by roy9495** [comment]
> 

Ok will do

**Comment by roy9495** [comment]
Can someone please review this #1265

**Comment by sammyhori** [comment]
Issue closed in #1452
