### ISSUE TITLE
Can these Python projects be added to the list?

### ISSUE THREAD

**Issue by Danny3** [MunGell/awesome-for-beginners#1258]
Hi!

Can these Python projects be added to the list?:

OpenSnitch application firewall:
https://github.com/evilsocket/opensnitch

PicoSnitch network traffic monitor:
https://github.com/elesiuta/picosnitch

SysMonTask system resources monitor:
https://github.com/KrispyCamel4u/SysMonTask

Maybe they are small an easy enough to start with and someone can also contribute something to them.

Thank you!

**Comment by sammyhori** [comment]
Unfortunately:
OpenSnitch has no issues opened under the "good first issue" label
PicoSnitch is inactive (10 months since last commit)
SysMonTask is inactive (3 years since last commit)

Therefore none of these repositories are valid to be added to the list anymore.
Feel free to re-request them if the situation in any of them change.

**Comment by Danny3** [comment]
Understandable and thank you very much for taking a look at the list!

As for SysMonTask, in the meantime I found a good replacement for it!
Which tries to do the same thing, with the same awesome interface, has more features and it's actively maintained:
https://missioncenter.io/
But since it's not hosted on Github, I don't know which language it uses.
I guess it could be C or C++.
Though looking at is building requirements I see "Python3" mentioned too.
So maybe there's some Python too.
Though seeing how many futures it has and how profession it is, I don't think it's good for beginners in any language.

**Comment by sammyhori** [comment]
Thanks for the help.
Their source code can be found here: https://gitlab.com/mission-center-devs/mission-center
It looks like it's mostly in C and Rust.
They do have [two good first issues](https://gitlab.com/mission-center-devs/mission-center/-/issues/?sort=created_date&state=opened&label_name%5B%5D=good-first-issue&first_page_size=20), but I am also unsure about adding them as the ratio of 2 appropriate issues out of 91 issues is not the greatest.
