### ISSUE TITLE
awesome-for-beginners is not actively maintained

### ISSUE THREAD

**Issue by c-mart** [MunGell/awesome-for-beginners#1275]
From `CONTRIBUTING.md`:

> The contributed repository must be maintained, have an active community...

The community is active here, but the maintainer @MunGell is not. The last commit to the main branch was 6 months ago. There are 71 open PRs.

Is it time to add more maintainers, or mark this project as deprecated / read-only?

**Comment by MunGell** [comment]
Hey Chris,

Thanks for bringing this up, are you volunteering to become a maintainer of this project?

**Comment by c-mart** [comment]
@MunGell I don't want to be the only maintainer, but I could be one of multiple, yes.

**Comment by MunGell** [comment]
Added you as a collaborator, so feel free to look into the PRs.
You can start with your own PR - look at how other Gitlab URLs are formatted and update your contribution to match it.

**Comment by MicahWSmith** [comment]
@MunGell I Would love to help maintain this project! Feel free to add me as a collaborator 🙂

**Comment by TimoTong** [comment]
Still 79 prs to be handled, come on guys!

**Comment by avinashji1302** [comment]
I would also love to help to maintain this project .....please add me as a collaborator

thank you!

**Comment by Bryon0** [comment]
You can add me as well. I'll do what I can. Thanks!

**Comment by OceanBerlinghieri** [comment]
I would like to mantain the project as a collaborator

Thank you!

**Comment by ho-ssain** [comment]
I'm interested in remaining involved with the project as a collaborator. You can add me also.

**Comment by jaybaba8085** [comment]
Hi @MunGell  I Would love to help maintain this project! Feel free to add me as a collaborator 🙂

**Comment by aishwaryamensinkai** [comment]
Hi @MunGell I'm interested in helping to maintain this project

**Comment by sammyhori** [comment]
@MunGell I would be glad to be added as a collaborator, so I can clean up and cut down on the PRs and Issues.

**Comment by MunGell** [comment]
Thanks everyone who offered help in this thread!

@sammyhori @aishwaryamensinkai I've added you both as collaborators, please check if you have all needed permissions to manage issues and pull requests here!

Thank you for your help!
