### ISSUE TITLE
ChessEngine `good-for-beginners` Java project

### ISSUE THREAD

**Issue by MrMystery10-del** [MunGell/awesome-for-beginners#1277]
Some base ideas of how it work:
Upon starting the application, the user will be directed to a menu screen that displays their current stats such as Elo and profile information.
Two buttons are present on this screen, allowing the user to choose between multiplayer and against AI modes.
Upon selecting the against AI option, the user is redirected to another screen where they can select an AI opponent from a list of unique algorithms, each with its own description.

After choosing their preferred AI opponent, the user can begin the game with a time limit of 10 minutes.
The in-game screen displays the time remaining, the game board, captured pieces, and the AI opponent.
When the user emerges victorious, they will earn additional Elo points based on their opponent's Elo rating.

https://github.com/MrMystery10-del/ChessEngine

**Comment by avinashji1302** [comment]
can I work on this??

**Comment by Zeran719** [comment]
could you assign this to me

**Comment by sammyhori** [comment]
Closing as this now an inactive repository.

Feel free to reopen this issue or a new issue if it becomes active again.
