### ISSUE TITLE
NodeOS

### ISSUE THREAD

**Issue by piranna** [MunGell/awesome-for-beginners#128]
[NodeOS](node-os.com) has the [level: easy - first bug](https://github.com/NodeOS/nodeos/issues?q=is%3Aopen+is%3Aissue+label%3A%22level%3A+easy+-+first+bug%22) label, but it has task both for Javascript, C, web development or system administration. How should I include it in the list?

**Comment by MunGell** [comment]
Hey @piranna 

Sorry for the delay - please include it in both sections of the list
