### ISSUE TITLE
Broken hyperlink

### ISSUE THREAD

**Issue by ndsvw** [MunGell/awesome-for-beginners#1294]
Hello, I found a broken hyperlink:
- [ ] https://meta.discourse.org/tags/starter-task (file: README.md, status code: 404)

**Comment by KetanParmar02** [comment]
Hey, @ndsvw i'm interested to resolve this issue can you assign to me?
so, i can resolve this issue and contribute in your project..
i hope you will give me this opportunity.

**Comment by ndsvw** [comment]
Hi @KetanParmar02, this is not my project, so I can't assign the issue to you.
But I guess, you could just fix this issue and create a pull request as long as you follow the [rules of this project](https://github.com/MunGell/awesome-for-beginners/blob/main/CONTRIBUTING.md)..

---

BTW: If you are experimenting with how to contribute to GitHub projects / how pull request work and are looking for more issues like this (about broken links), the issues I opened in these projects during the last month could be interesting:

![Screenshot_20230601_221059](https://github.com/MunGell/awesome-for-beginners/assets/21332313/e7d0dc6b-95ce-4c24-9eb8-ecd018db8b38)

**Comment by KetanParmar02** [comment]
can you suggest me what should I do next now??

**Comment by ndsvw** [comment]
What you want to do is **creating a pull request**. [This is a video about it](https://yewtu.be/watch?v=rgbCcBNZcdQ).

1) Fork the repository
2) Clone the fork
3) Create a new branch and name it like you want (e.g. "linkfix")
4) Fix the broken link in a text editor of your choice. Save the file..
5) Create a commit with a message that you fixed the hyperlink and mention "#1294" so that one knows that it's about this issue.
6) Push the commit to your fork of the project
7) Go to GitHub and open the page of your fork. There should be a yellow notification asking you to create a pull request. Do that..
8) Wait until the project owner(s) accept your pull request

**Comment by sammyhori** [comment]
Closed by #1318
