### ISSUE TITLE
Update Table of Contents with better icons 

### ISSUE THREAD

**Issue by Akshayp02** [MunGell/awesome-for-beginners#1325]

**Comment by Sumansarmah123** [comment]
can you leave the link to the repository which has the code on the table of contents,so that we can improve it!

**Comment by Akshayp02** [comment]
On this section https://github.com/MunGell/awesome-for-beginners

**Comment by Charity10** [comment]
what icons are we to change??
the bullets or we should add an image before each heading??

**Comment by Akshayp02** [comment]
Yes for example ![IMG-20230817-WA0026.jpg](https://github.com/MunGell/awesome-for-beginners/assets/95123298/52e4c0e1-1737-47d9-9ec2-4d9bc134f2d7)

**Comment by motuncoded** [comment]
Can you assign this to me? I think I get what you intend to do

**Comment by Akshayp02** [comment]
hey @motuncoded I'm appreciate with your Enthusiasm but I've already opened this issue, so please can you see any other section.😊

**Comment by Akshayp02** [comment]
❤

**Comment by Akshayp02** [comment]
Look better
