### ISSUE TITLE
Python Projects

### ISSUE THREAD

**Issue by Sukanyasingh3** [MunGell/awesome-for-beginners#1367]
Here are 2 of my python projects, Could these be added to the list?

- [PyroDetect](https://github.com/Sukanyasingh3/PyroDetect) _(label: good-first-issue)_ <br> Tool to detect fire in CCTV Images using a Tensorflow CNN Classification Model. 

- [AgroAid](https://github.com/Sukanyasingh3/AgroAid) _(label: level:starter)_  <br> A plant disease detector using ResNet50

**Comment by sammyhori** [comment]
Closed as requested repositories is closed
