### ISSUE TITLE
Add NextGenCSS for CSS or SASS

### ISSUE THREAD

**Issue by rudransh61** [MunGell/awesome-for-beginners#1374]
Hi, 
Your repository is very good for helping junior engineers to make their first pr,

I found a repository called NextGenCSS [https://github.com/rudransh61/NextGenCSS-](https://github.com/rudransh61/NextGenCSS-)
It is a very beginner friendly and easy to start with some basic knowledge of CSS and sass

I hope you will add this in your repo

Thanks for reading

**Comment by rudransh61** [comment]
@MunGell 
Pls review this issue

**Comment by sammyhori** [comment]
Sorry but I'm closing this issue as this now an inactive repository.

Feel free to reopen this issue or a new issue if it becomes active again.
