### ISSUE TITLE
Need Guidance

### ISSUE THREAD

**Issue by Chirag-123-jain** [MunGell/awesome-for-beginners#1375]
Hi have the knowledge of frontend as well as backend but i have never been into open source so how i can give my contribution as a freasher

**Comment by devwork260802** [comment]
Fix Issue #1375

just search for the project through search tab and find on the basis of languages like html, css or any other and fix the issue and reply to them that you fixed it.

**Comment by Chirag-123-jain** [comment]
i have one confusion how will get to know in which project what is the issue

**Comment by Marionkay-star** [comment]
> r

Chat me up

**Comment by bannarama2** [comment]
From what I understood (I'm also new to open source contribution) is that every repository that has a project usually has a page that allows people to submit issues that are present (bugs, new feature suggestions, etc.) So looking at those "forum" posts might help you know what to work on.

**Comment by sammyhori** [comment]
Here is a guide for [making your first open source contribution](https://github.com/readme/guides/first-oss-contribution)
And here is a guide for [understanding issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues)

**Comment by sammyhori** [comment]
I am closing this because it is stale.
I have provided some guides to help answer the questions people had.

**Comment by bannarama2** [comment]
Thanks sammy 🫡

**Comment by sammyhori** [comment]
No problem :)
Just got permissions for this repo so have been doing a lot of cleaning up
