### ISSUE TITLE
How can I Add a New Go Project

### ISSUE THREAD

**Issue by PrimmaAnna** [MunGell/awesome-for-beginners#1380]
[Apache Answer](https://github.com/apache/incubator-answer) (label: good-first-issue)
A Q&A platform software for teams. Built with Golang and ReactJS, under Apache-2.0 license.

**Comment by sammyhori** [comment]
All projects can be added to the `data.json`.

Currently, however, this repository doesn't currently have any issues labelled as beginner friendly (`good first issue` in this case) so wouldn't be accepted as an addition as it is right now.
