### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by sumedhakoranga** [MunGell/awesome-for-beginners#1384]
Where can I find the issues? I would love to make some Contributions.

**Comment by Mohsin-963** [comment]
I think... we are supposed to visit the given project links, and find issues there.
There is a list of language on first page.

Follow your preferred language.

Select the project of interest.

Visit their issues tab.

Find the issues you want to contribute on.

I think that's how it supposed to go, I guess? I'm not entirely sure I am new here as well.
