### ISSUE TITLE
Add an Expo e-commerce complete project

### ISSUE THREAD

**Issue by huanghanzhilian** [MunGell/awesome-for-beginners#1396]
C-Shopping-RN APP

This is a complete App developed by React Native (Expo). It is a beautiful e-commerce shopping application.

## Use technology

- React Native
- Redux Toolkit
- RTK Query
- Expo Router
-NativeWind

App open source address: https://github.com/huanghanzhilian/c-shopping-rn
Full stack open source address: https://github.com/huanghanzhilian/c-shopping

**Comment by sammyhori** [comment]
Thanks for the request! Unfortunately these repositories are both now somewhat inactive.

Because of this I believe they shouldn't be added to the list. Feel free to open a new issue if they become active and follow all the requirements (found in the contributing file) again.
