### ISSUE TITLE
Awesome 

### ISSUE THREAD

**Issue by obed4life** [MunGell/awesome-for-beginners#1404]

**Comment by Ekundayo39283** [comment]
Hi there, please explain the issue here and if there's no issue you can proceed to close the issue in other to clear traffic

_Thank you_

**Comment by rishabdev2997** [comment]
Hi there, please explain the issue here and if there's no issue you can proceed to close the issue in other to clear traffic

Thank you

**Comment by sammyhori** [comment]
Closed due to a lack of an issue description
