### ISSUE TITLE
Game of Life 404

### ISSUE THREAD

**Issue by StackOverflowIsBetterThanAnyAI** [MunGell/awesome-for-beginners#1406]
hey, I found that the link to the TypeScript: game-of-life site is returning a 404 error

current link: https://github.com/TroyTae/game-of-life

**Comment by Casmei** [comment]
This link is also broken 😞

**Comment by FaridFArab** [comment]
This is the correct link:
https://github.com/RuyiLi/cursed-typescript
but need to change some descriptions in README file.
