### ISSUE TITLE
No good-first-issue label on Neovim

### ISSUE THREAD

**Issue by mcagriaksoy** [MunGell/awesome-for-beginners#1437]
Attached project:
[Neovim](https://github.com/neovim/neovim) (label: good-first-issue)
Vim-fork focused on extensibility and agility.

has no "good-first-issue" label, maybe you consider to remove that project from the list.

**Comment by Jay-Karia** [comment]
I agree

**Comment by afrinashar** [comment]
I would like to work on this.
