### ISSUE TITLE
I'm first timer but I want to create a repository 

### ISSUE THREAD

**Issue by RichardKiisa** [MunGell/awesome-for-beginners#1456]

**Comment by RichardKiisa** [comment]
<!Doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page title</title>
</head>
<body>
    
</body>
</html>

**Comment by sammyhori** [comment]
What was this issue for? Were you just trying to get the "first issue" achievement? I see you managed to make your own repository

**Comment by RichardKiisa** [comment]
> What was this issue for? Were you just trying to get the "first issue" achievement? I see you managed to make your own repository

Yes but I didn't know how to use it but per now am catching up with such

**Comment by sammyhori** [comment]
Okay, that's good to hear 😄.
Make sure to check out [the docs](https://docs.github.com) for extra help navigating Git and GitHub.
If you no longer need this issue please [close it](https://docs.github.com/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue), just to help clear it from the list of current issues.

**Comment by sammyhori** [comment]
Closed as stale
