### ISSUE TITLE
Reference @first_tmrs_only Twitter bot.

### ISSUE THREAD

**Issue by musically-ut** [MunGell/awesome-for-beginners#153]
I am the maintainer of the Twitter bot [@first_tmrs_only](https://twitter.com/first_tmrs_only) which tweets about `first-timers-only` issue as they are created on GitHub. The bot is [open source](https://github.com/musically-ut/first-timers-only-bot) and I may add support for other beginner friendly labels [at some point](https://github.com/musically-ut/first-timers-only-bot/pull/3).

It already has a decent following of ~1000 users and has been active for 1.5 years.

With your permission, I would like to add a plug for the bot on this _awesome_ resource. :)

**Comment by MunGell** [comment]
Hey @musically-ut 

Sorry for the delay, feel free to create a PR!
