### ISSUE TITLE
Help me.....!

### ISSUE THREAD

**Issue by kenshimota** [MunGell/awesome-for-beginners#181]
Buenas tardes, noches y días solamente quería saber si alguno me podría ayudar en la contribución de un  open source soy nuevo en ello de verdad no soy un buen programador aun  tengo que aprender mucho así que me interesa

**Comment by gbasisty** [comment]
Si, no hay problema. Que necesitas?

**Comment by kenshimota** [comment]
que alguien me guie en que y de que forma se puede contribuir pues es mi primer project open source  y mi manejo de programacion es en c algo de c++, php y javascript tengo algunos repositos en mi perfil si quieren verlos ayudarme a estructurar mejor mis codigos y ayudarme a mejorar pues no soy muy habil en esto pero me gustaria ir aprendiendo muchisimo mas :100:  :paintbrush:

**Comment by Roshanjossey** [comment]
@kenshimota, I’m working on a project to help beginners get started on contributing open source projects.
https://github.com/Roshanjossey/first-contributions/
I'm sure you'll find it useful.

@MunGell, does it make sense to add a link to first contributions at the beginning of Readme?

**Comment by kenshimota** [comment]
@Roshanjossey Creo que el Readme tiene enlaces a las app mas conocidas de open source debido a que a esta se les hacen muchas contribuciones por ejemplo phpMyAdmin lo traen casi todos los wamp, Lamp, Mamp, que son los servidores de para los distintos lenguajes como python, php o perl y me gustaria apoyarte en la contribucion de tu codigo si me permites

**Comment by Roshanjossey** [comment]
@kenshimota, take a look at this https://github.com/Roshanjossey/first-contributions/blob/master/translations/README.es.md

**Comment by kenshimota** [comment]
@Roshanjossey Gracias por tu ayuda espero que puedas leer mis repositositos y comentarlos esto me hara crecer en la programacion ya que lo que al vez yo no vea como un problema, tu si lo llegues a detectar asi ademas estoy en un proyecto de c++ muy interesante dentro de unos dias lo subire en cuanto pueda
