### ISSUE TITLE
Add link under "Typescript" for tslint

### ISSUE THREAD

**Issue by aervin** [MunGell/awesome-for-beginners#182]
Would be great to add a link for [`tslint`](https://github.com/palantir/tslint/issues) under "Typescript." The repo often adds "good first issue" tags and could use some new contributors.

**Comment by MunGell** [comment]
Hi @aervin 

Please feel free to create a PR for this addition!

**Comment by trivikr** [comment]
TSLint was added in #187
This issue can be closed
