### ISSUE TITLE
CMD.IO

### ISSUE THREAD

**Issue by larsonthekidrs** [MunGell/awesome-for-beginners#185]
You need to add cmd.io to the list under Golang. This project is by glider labs.

**Comment by Antrony** [comment]
check

**Comment by MunGell** [comment]
Hi @larsonthekidrs are you planning to create a PR?

**Comment by larsonthekidrs** [comment]
@MunGell what do you mean by that?

**Comment by MunGell** [comment]
I mean that if you think that there is a project that should be added to the list you could easily create a pull request (PR) to add it there.

Please make sure the project and the PR you create are following [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md).

**Comment by Antrony** [comment]
Antro A has invited you to join Antro A's Team

Joining the team will give you access to the team's pipelines, contacts and email

Current Team Members

Owners: Antro A

Members: asterisk-dev@lists.digium.com, reply@reply.github.com, Antro A, deepa@geekyspider.com, dev@wso2.org

Current Pipelines

Bugs, Job Applications, Investment Deals, Blank

Accept Invite
( https://www.streak.com/teaminvite?email=reply@reply.github.com&team=agxzfm1haWxmb29nYWVyEQsSBFRlYW0YgIDIsOWf-QgM&utm_content=Team+Invite+Email&utm_medium=email_action&utm_name=App+Transactional+-+Team+Invite+Email&utm_source=customer.io )

See team details ( https://www.streak.com/teaminvite?email=reply@reply.github.com&team=agxzfm1haWxmb29nYWVyEQsSBFRlYW0YgIDIsOWf-QgM&utm_content=Team+Invite+Email&utm_medium=email_action&utm_name=App+Transactional+-+Team+Invite+Email&utm_source=customer.io )

Streak is a CRM built right into your inbox. Streak is great for sales, customer support, hiring, deal flow and more. If you don’t have Streak yet, no problem, just click the Accept link above to get Streak.

( https://www.streak.com/careers?utm_content=Team+Invite+Email&utm_medium=email_action&utm_name=App+Transactional+-+Team+Invite+Email&utm_source=customer.io )
