### ISSUE TITLE
Piwik is now known as matomo

### ISSUE THREAD

**Issue by valkheim** [MunGell/awesome-for-beginners#192]
"Piwik, the community project, will now become Matomo. The only change is our name, everything else stays the same." from https://matomo.org/blog/2018/01/piwik-is-now-matomo/

The following lines in the readme should be adapted
"Piwik (label: Easy Pick)
Piwik is the leading Free/Libre open analytics platform."

**Comment by MunGell** [comment]
Thank you @valkheim 

@usaandi have fixed this issue, so I am closing it
