### ISSUE TITLE
Make a Website

### ISSUE THREAD

**Issue by nebrelbug** [MunGell/awesome-for-beginners#199]
I think that it would be a great idea to have a website for this project, where users could easily see qualifying projects. Anybody else think this would be a good idea? I'd be happy to help with building it.

**Comment by marcelosdm** [comment]
I agree!!

**Comment by ascii-dev** [comment]
I also agree and I would be glad to help with building it... @nebrelbug should we build it???

**Comment by NassimBounouas** [comment]
Totally agree with this suggestion !

**Comment by rinilkunhiraman** [comment]
Yes and I would like to be part..

**Comment by nebrelbug** [comment]
Great! @ascii-dev @rinilkunhiraman @NassimBounouas @marcelosdm if @MunGell likes this idea too, he could create a branch and we could fork it. Otherwise, we could fork now and start working... what do you think?

**Comment by ascii-dev** [comment]
I think we should fork now and start work. I think if @Mungell sees what we've achieved, it'll help him make his decision. @nebrelbug

**Comment by nebrelbug** [comment]
That sounds good. Should I create the fork?

**Comment by ascii-dev** [comment]
Yes @nebrelbug. You create the fork, we'll fork from yours and start working on it.

**Comment by nebrelbug** [comment]
Done. https://github.com/nebrelbug/awesome-for-beginners

**Comment by ascii-dev** [comment]
Great. I'll look into it now. So, what are we developing the website with and how's it gonna function? What do you suggest?

**Comment by nebrelbug** [comment]
I think for now, at least, we should use GitHub Pages. As far as Jekyll vs. HTML, I don't really have a preference. You?

**Comment by ascii-dev** [comment]
Yeah... We can do html for now and get to hear what @MunGell feels first.

**Comment by nebrelbug** [comment]
Sounds good

**Comment by marcelosdm** [comment]
I forgot to say that I wanna help too!! I don't know exactly how , but count on me!!

**Comment by nebrelbug** [comment]
Great! Thanks @marcelosdm!

**Comment by wchandler2018** [comment]
Hi, I am beginner but I would love to be involved if possible

**Comment by nebrelbug** [comment]
Great! The fork is at https://github.com/nebrelbug/awesome-for-beginners. Thanks @wchandler2018!

**Comment by JohnSquare** [comment]
Hi! I am beginner too and I would like to participate with you! I have a question... Why do we fork? Isn't more logical do a new repository for a new project? (Sorry for my english, I am learning yet....)

**Comment by nebrelbug** [comment]
@JohnSquare, we're forking because the plan is to eventually, if @MunGell agrees, merge our website into this repository. We're using the same projects too.

**Comment by JohnSquare** [comment]
Thanks for your answer @nebrelbug, but i have a lot of questions about this web, where could I see more information? I am really excited about this project.

**Comment by nebrelbug** [comment]
You can check out the fork so far at https://github.com/nebrelbug/awesome-for-beginners, and check out the issues & pull requests

**Comment by tushar-nitave** [comment]
I would like to be part of it.

**Comment by JohnSquare** [comment]
That's it @nebrelbug. What is the web idea?

**Comment by gauravsood1410** [comment]
I would love to get involved in this too, but I'm a noobie, can anyone suggest me how do I immediately get started with it?

**Comment by JefMari** [comment]
Question, Why need to fork where you can simply just create a github page with the repository?

**Comment by nebrelbug** [comment]
@JefMari we wanted to do that so we can have a polished website when we submit a pull request. @gauravsood1410 Check out our repo and create a repo asking how! I'm sure there are plenty of things you could do.

**Comment by lonewolf9277** [comment]
Hi I'd like to be involved too.

**Comment by s18692001** [comment]
I'm interested in this project!

**Comment by mrcolo** [comment]
Hi! I would like to contribute too.

**Comment by ShuviDola** [comment]
Hello, I also want to help.

**Comment by Meikay** [comment]
Hi @nebrelbug ! I'm new, could I help build the website too?

**Comment by hariprasad01** [comment]
Hey guys, can i help in this project too?

**Comment by mrcolo** [comment]
Why don't we create a slack team?

**Comment by nebrelbug** [comment]
This sounds great! For anyone who wants to help, or has questions about the project, head over to the forked repo.

**Comment by taruchit** [comment]
Hi, I am too a beginner; and would want to learn & contribute to the project.

**Comment by nebrelbug** [comment]
@taruchit that'd be great! Head over to the repo [here](https://github.com/nebrelbug/awesome-for-beginners)

**Comment by sonusharma07** [comment]
Hi, i would like to contribute in your project ,this will be my first project if you count me in .

**Comment by nebrelbug** [comment]
Sounds great! We’d love your help!

**Comment by keerthanasriranga** [comment]
Hey, I'd like to contribute too.

**Comment by aeidelos** [comment]
Yes, and i also want to contribute :+1:

**Comment by nebrelbug** [comment]
@keerthanasriranga @aeidelos Great! Head over to the repo!

**Comment by lloydlions** [comment]
Hello. Please count me in, i want to join this project. Thanks.

**Comment by nebrelbug** [comment]
Thanks @lloydlions!

**Comment by yati1998** [comment]
Hello, Can I join this project now?
Thanks

**Comment by tayarndt** [comment]
I agree. Lets do it

**Comment by tayarndt** [comment]
I want in also.

**Comment by nebrelbug** [comment]
@tayarndt, @yati1998 Great! Head over to the forked repo and make a pull request! See above or in the forked repo for ideas.

**Comment by stanmill** [comment]
Im in

**Comment by yati1998** [comment]
Ohk sure..I haven't looked into the idea but will shortly check the repo...
It will be great if we could have a slack group for the easy conversation
and discussion about the website

**Comment by robertVclements** [comment]
I would also like to get involved in this project. Can I still join?

**Comment by nebrelbug** [comment]
@yati1998 @robertVclements @stanmill any help is appreciated!

**Comment by stanmill** [comment]
Hey lets create a slack group

**Comment by nebrelbug** [comment]
@stanmill why don't you suggest that on the repo

**Comment by stanmill** [comment]
Cuz i was on my phone when I wrote it soo I don’t have the url of the git
repo

**Comment by nebrelbug** [comment]
@stanmill great! Sorry, that was meant to be a suggestion, not a criticism.

**Comment by Pkalra7** [comment]
Room for other junior developers/beginners to join in?

**Comment by nebrelbug** [comment]
Yes

**Comment by stanmill** [comment]
Everyone this is the slack group join 
https://join.slack.com/t/awesome-for-beginners/shared_invite/enQtNDM0OTEwMDYwNTQ1LWQ4NDc0NDgxNzY3YjEzMTZlZjY0MGMyNjVkMTZlMWNmMTdmMjllYzk1NmQ0MjA1MmY1OWZkNmYyYjkyZjIxN2E

**Comment by Chaitanyate** [comment]
Iam also likely to work upon this project

**Comment by sushil763** [comment]
I also want to contribute to the project.

**Comment by kehsiberry** [comment]
Can I contribute? 🤗
New here

**Comment by koolamusic** [comment]
I think this is a great idea, 
- Has anyone thought about using Jekyll and Github Pages

I think it should be pretty straightforward to use it and hit the ground running. while maintaining contributions via a readme

**Comment by electronF** [comment]
Hello!
How are You?
What project are you talking about?

Le samedi 27 octobre 2018, Andrew Miracle <notifications@github.com> a
écrit :

**Comment by koolamusic** [comment]
I am referring to this Repo 
hosting it using gh-pages Github Pages 

creating a gh-pages branch will automatically publish this readme to a Github pages and give this repo a website URL, with some styling it should look amazing.
