### ISSUE TITLE
Some of projects have not issues for label or archived.

### ISSUE THREAD

**Issue by oxmap** [MunGell/awesome-for-beginners#222]
I just went through JS section and saw that many projects has no issues for corresponding labels. And some of projects archived at all.

**Comment by vvscode** [comment]
Only one is archived (https://github.com/MunGell/awesome-for-beginners/pull/223) and the fact, that right now there are no labeled issues in some repos - so what? it might be

**Comment by oxmap** [comment]
Firstly archived project  in pull request.  Close.
