### ISSUE TITLE
slack

### ISSUE THREAD

**Issue by stanmill** [MunGell/awesome-for-beginners#235]
can someone make a slack group so that its easy for us to communicate.

**Comment by vvscode** [comment]
https://join.slack.com/t/awesome-for-beginners/shared_invite/enQtNDM0OTEwMDYwNTQ1LWQ4NDc0NDgxNzY3YjEzMTZlZjY0MGMyNjVkMTZlMWNmMTdmMjllYzk1NmQ0MjA1MmY1OWZkNmYyYjkyZjIxN2E
