### ISSUE TITLE
Removing un active projects from the list

### ISSUE THREAD

**Issue by vjs3** [MunGell/awesome-for-beginners#281]
There are some projects on the list which are not active anymore like this [one](https://github.com/johnstonbl01/clementinejs). I would love to remove those to keep the list up to date.

Let me know if I can make a PR for same.

**Comment by anjaliparmar** [comment]
Hello,
I'm learning python, and i want to contribute in your project.

**Comment by MunGell** [comment]
Hi @vjs3 

You don't need my permission to create a PR :)

Removing not active project will be very helpful, I will appreciate your contribution.
