### ISSUE TITLE
add aurelia.js to JavaScript category

### ISSUE THREAD

**Issue by kam773** [MunGell/awesome-for-beginners#306]
Hello, I would like to contribute to this project adding aurelia.js framework to javascript category.

**Comment by vvscode** [comment]
do they have beginners label? PR is welcome

**Comment by kam773** [comment]
nope, didn't check it earlier

wt., 27 lis 2018 o 17:13 Vasiliy Vanchuk <notifications@github.com>
napisał(a):

**Comment by vvscode** [comment]
Looks like it's worth first to check ))
