### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by ezaquarii** [MunGell/awesome-for-beginners#324]
I see that PRs are not being merged since 2017. Is it still alive?

**Comment by arnavb** [comment]
You probably meant December 2018 but yeah there has been almost 3 months of inactivity.

**Comment by MunGell** [comment]
Yes, but I am struggling with the volume of PRs and reviews required.
So PR merges are slow and take time

You can help by going through the PRs and :+1 them if they meet CONTRIBUTING guidelines.
