### ISSUE TITLE
Tooling

### ISSUE THREAD

**Issue by stevemao** [MunGell/awesome-for-beginners#33]
The whole list is about languages. Would you consider adding some tooling to the list? EG: I believe my list: https://github.com/stevemao/awesome-git-addons is beginner friendly for new git users. Also https://github.com/you-dont-need/You-Dont-Need-GUI is a great place for learning simple cli commands that you would probably do in GUI.

**Comment by JefMari** [comment]
I think this would fall to category 'GIT' or 'CLI' .

**Comment by stevemao** [comment]
The concern was I don't want "GIT" to sound like a language.

**Comment by MunGell** [comment]
Hi @stevemao 

Thanks for your contribution.

There many tools, articles and repositories that would be very helpful for beginners, however purpose of this list is to provide beginners with a list of real-world projects where they could practice their skills and that welcome their contribution.

**Comment by stevemao** [comment]
Thanks @MunGell
