### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by paramt** [MunGell/awesome-for-beginners#341]
On the second line of the README

> Inspired by [First Timers Only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455#.vsu847e81) blog post and [YourFirstPR](http://yourfirstpr.github.io/) project.

The `First Timers Only` link leads to a deleted blog post... I think it's better to change it to 

> Inspired by the [YourFirstPR](http://yourfirstpr.github.io/) project.

**Comment by MunGell** [comment]
Hi @paramt 

Looks like @kentcdodds has moved this post to his own blog, it is now available here: https://kentcdodds.com/blog/first-timers-only

Please feel free to create a PR to correct the link

Thanks!

**Comment by kentcdodds** [comment]
Thanks for keeping that updated!
