### ISSUE TITLE
Non-GitHub projects like Drupal

### ISSUE THREAD

**Issue by DouglasUrner** [MunGell/awesome-for-beginners#352]
[Drupal.org](https://drupal.org) has a culture that is very welcoming to beginners and a well established mentoring program as well. But, although Drupal uses git...
* It isn't hosted on GitHub, which means
* There are no GitHub issue labels.
Would it still be a welcome addition to the list (with information in the description on how to get started)?

**Comment by MunGell** [comment]
Hi @DouglasUrner 

Yes, please feel free to create a PR with a link to the most appropriate place where beginners should start their journey to contribute to Drupal.

Thanks

**Comment by MunGell** [comment]
I guess the most appropriate link will be https://www.drupal.org/getting-involved-guide

Something like this:

- [Drupal](https://www.drupal.org/getting-involved-guide
) _(label: N/A, link to external website)_ <br> Leading open-source CMS for ambitious digital experiences that reach your audience across multiple channels.
