### ISSUE TITLE
"Your First PR" project is inactive

### ISSUE THREAD

**Issue by dmitrij-schmidt** [MunGell/awesome-for-beginners#362]
According to their tweet https://twitter.com/yourfirstpr/status/1067159601894883328 and looking at activity feed, "Your First PR" project is inactive for about a year.

It might be good to remove it from README.

**Comment by MunGell** [comment]
Thanks @dmitrij-schmidt 

Feel free to create a PR to remove this link from the repo

**Comment by Mgosi** [comment]
Hello, I created a PR to remove the link from the README file. Please have a look. 
Thank you

**Comment by Mgosi** [comment]
#366

**Comment by vvscode** [comment]
I see the link in section `Inspired by...` so see no point in removing the link (IMHO)

**Comment by gmonu** [comment]
Thank you so much @dmitrij-schmidt

I see the link and created a PR to remove the link from your readme file . Please find it yourself and you will not get any error
