### ISSUE TITLE
In the Python session of the README

### ISSUE THREAD

**Issue by Shi-Jianmin** [MunGell/awesome-for-beginners#590]
When clicking the mitmproxy link, no result is matched.

>[mitmproxy](https://github.com/mitmproxy/mitmproxy/labels/good-first-contribution) (label: good first contribution)

I couldn't find the "good first contribution" label on the mitmproxy.
It's better to change.
Maybe it's changed to the "help wanted" label on the README.

**Comment by vvscode** [comment]
PR is welcome

**Comment by LuisMBarrera** [comment]
Hi! I just applied this changes on the pull request #591. Hope it's okay because I didn't ask prior if I could take this issue.

**Comment by MunGell** [comment]
Thanks @Shi-Jianmin @vvscode @LuisMBarrera !
