### ISSUE TITLE
Alphabetic order on suggestions

### ISSUE THREAD

**Issue by polilluminato** [MunGell/awesome-for-beginners#602]
I see that **Table of Contents** is in alphabetic order but the suggestions inside each category not, take for example **.NET**,**C#**, **GO**.
I know that in the guidelines new addition goes to the bottom of the relevant category but I think that reading list in alphabetic order is much easier, for example, if I want to search for something.

I could make some  PR to fix orders if it's useful.

**Comment by polilluminato** [comment]
I think that the Issue is still relevant , I'm waiting for a reply from the mantainer.

**Comment by MunGell** [comment]
Hi @polilluminato 

Thanks for the offer and sorry for the delay!
Would you be able to create PRs for this re-ordering, I would suggest having a separate PR per category if that works for you - it will be easier to do the checks that way.

Let me know what you think!

**Comment by polilluminato** [comment]
> Hi @polilluminato
> 
> Thanks for the offer and sorry for the delay!
> Would you be able to create PRs for this re-ordering, I would suggest having a separate PR per category if that works for you - it will be easier to do the checks that way.
> 
> Let me know what you think!

Yeah I think It's a good idea, in this way we can create small pull request and I'll try to do it in a correct way and not like #605
