### ISSUE TITLE
The project linked "Operation Code" is archived, read-only

### ISSUE THREAD

**Issue by pandaseal** [MunGell/awesome-for-beginners#609]
The project Operation Code, listed under Ruby, is archived and converted to read-only (at least the sub-repo that is linked). New link could probably be: https://github.com/OperationCode/START_HERE

**Comment by vvscode** [comment]
https://github.com/MunGell/awesome-for-beginners/pull/608

**Comment by MunGell** [comment]
stalebot, still relevant

**Comment by MunGell** [comment]
#608 closed this
