### ISSUE TITLE
Spamming

### ISSUE THREAD

**Issue by ds-designs** [MunGell/awesome-for-beginners#620]
Watching/Starring this repo causes you to get bombarded with spam emails.

**Comment by MunGell** [comment]
Hi @ds-designs 

This is standard GitHub functionality and is not specific to this particular repository. Any popular repository would cause that to your inbox if you will start watching it without adjusting your Notifications preferences.

Refer to https://github.com/settings/notifications page if you want to change what you want to receive emails on. Also, starred repositories will not be sending you notifications, so all you need to do is "unwatch" this project.
