### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by JefMari** [MunGell/awesome-for-beginners#63]
[Hanami](https://github.com/search?utf8=%E2%9C%93&q=user%3Ahanami+state%3Aopen+label%3Aeasy&type=Issues&ref=searchresults) has broken link.

**Comment by MunGell** [comment]
@JefMari thanks for checking

Hanami have no relevant issues yet, but they promised to fix it soon.

**Comment by JefMari** [comment]
Should the link change to this? [Hanami](https://github.com/hanami/hanami/labels/easy)
or not?

**Comment by MunGell** [comment]
They have several repositories and want to link to all "good for beginners" issues with one link, hence link is to search results.

It is not the most easy to read way of displaying issues, but it will allow us not to have a dozen of links to sub-repositories of one project.

I will think of how to deal with projects of that structure to present it in a better way here.

**Comment by JefMari** [comment]
For now, will closed this.
