### ISSUE TITLE
HTML/CSS Section

### ISSUE THREAD

**Issue by NeOMakinG** [MunGell/awesome-for-beginners#634]
That would be awesome to have an HTML/CSS section, we've some good first issue on PrestaShop repository related with that section

What do you think ? I can do the PR if you want.

**Comment by MunGell** [comment]
Hey, sorry for the delay, sounds good to me, feel free to add new section

**Comment by NeOMakinG** [comment]
After some meetings with my team, it looks like we decided to stay in the PHP section, regarding to add more good first issues linked with PHP.

Thanks, 
have a good day.
