### ISSUE TITLE
How about using the `/contribute` from GitHub instead of fixed labels on the URLs?

### ISSUE THREAD

**Issue by tiagostutz** [MunGell/awesome-for-beginners#645]
I was checking some repos and I noticed that the label that the list here is pointed to either does not have any issue assigned or the mantainers changed the used label for beginners.
What do you think about changing the URLs that points to a specific label by the `/contribute` URL that GitHub created for this porpuse (https://github.blog/2020-01-22-how-we-built-good-first-issues/).

For example: 
The current Dragula URL (https://github.com/bevacqua/dragula/labels/first-timers-only)

<img width="1017" alt="Captura de Tela 2020-04-30 às 15 24 38" src="https://user-images.githubusercontent.com/3986989/80745472-c03c8100-8af6-11ea-84bb-c64a1a1606d1.png">

would become https://github.com/bevacqua/dragula/contribute:

<img width="1028" alt="Captura de Tela 2020-04-30 às 15 24 48" src="https://user-images.githubusercontent.com/3986989/80745491-c5013500-8af6-11ea-81c3-51960220bb6e.png">

**Comment by andyguerra** [comment]
> I was checking some repos and I noticed that the label that the list here is pointed to either does not have any issue assigned or the mantainers changed the used label for beginners.
> What do you think about changing the URLs that points to a specific label by the `/contribute` URL that GitHub created for this porpuse (https://github.blog/2020-01-22-how-we-built-good-first-issues/).
> 
> For example:
> The current Dragula URL (https://github.com/bevacqua/dragula/labels/first-timers-only)
> 
> <img alt="Captura de Tela 2020-04-30 às 15 24 38" width="1017" src="https://user-images.githubusercontent.com/3986989/80745472-c03c8100-8af6-11ea-84bb-c64a1a1606d1.png">
> 
> would become https://github.com/bevacqua/dragula/contribute:
> 
> <img alt="Captura de Tela 2020-04-30 às 15 24 48" width="1028" src="https://user-images.githubusercontent.com/3986989/80745491-c5013500-8af6-11ea-81c3-51960220bb6e.png">

I think that's actually a very good idea

**Comment by tiagostutz** [comment]
I was checking out the [contribution guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md) and it states a link format that expects to use label and I was thinking that this PR would be almost a "breaking change" in this repo... it would be great if on of the repo maintainers - or even @MunGell - could give a bit heads up here before I start this...
