### ISSUE TITLE
Update Hugo label and link

### ISSUE THREAD

**Issue by mitchellroe** [MunGell/awesome-for-beginners#693]
The Hugo project label linked to from the README, `exp/beginner`, appears to have been deleted form the project.

**Comment by Parimalisgreat** [comment]
do i just need to add exp/begineer to the README file

**Comment by ZachHoskins** [comment]
It just appears that the exp/beginner label doesn't exist inside the Hugo project in Github. I didn't see any other beginner-friendly labels in the Hugo project.

**Comment by crew-guy** [comment]
Alright. So is it ok if I just read through the Hugo project and add these labels wherever you specify or where I feel they're required ?

**Comment by mishscien** [comment]
I am new to this!. i need learn more

**Comment by MunGell** [comment]
Thanks for flagging!
New label/link should be: https://github.com/gohugoio/hugo/labels/GoodFirstIssue

**Comment by MunGell** [comment]
Oh, sorry for all those updates, I see @unrealnerd has already created a PR for this fix: #953

**Comment by Ayushi271** [comment]
Hii
Can you assign this issue to me?

**Comment by Ayushi271** [comment]
Can you please review  the PR #1026
