### ISSUE TITLE
Adding for python in README.md

### ISSUE THREAD

**Issue by jobinkeecheril** [MunGell/awesome-for-beginners#702]
Adding https://github.com/tasnimzotder/hactoberfest-2020 for python developers

**Comment by sumana-19** [comment]
Hello @jobinkeecheril , what exactly do I have to do here? Could you please clarify and then assign this to me?

**Comment by roshnaeem** [comment]
Hey @jobinkeecheril, I want to work on this PR. Do I have to add this link to python projects listed at https://github.com/mungell/awesome-for-beginners#python ?

**Comment by kirtirajsinh** [comment]
I want to Contribute to this issue. How can I Get Started.

**Comment by jatinjain001** [comment]
I want to contribute in it??please assign it to me

**Comment by NikhilPrasad0497** [comment]
I want to contribute in this, Please let me know what needs to be done
