### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MunGell/awesome-for-beginners#711]
so as to clarify reusability

**Comment by AnshMishra2001** [comment]
@Daniel-Mietchen could you please elaborate on the task to be done. I will be more than willing to contribute.

**Comment by sai-lalith** [comment]
Hey, I have done a pull request regards this and hope MIT license would useful

**Comment by MunGell** [comment]
Hi all,

For license please refer to the bottom of the main page.
