### ISSUE TITLE
Any chance of creating a List of elm-lang related projects?

### ISSUE THREAD

**Issue by mhoare** [MunGell/awesome-for-beginners#77]

**Comment by MunGell** [comment]
Hi @mhoare 

Absolutely, there are no restrictions on which languages are listed here.
Please feel free to create a new category if you have a beginner-friendly repository in mind.

Or let me know which Elm-based project we are missing here and I will add it together with the category.

Thanks

**Comment by JefMari** [comment]
+1

**Comment by mhoare** [comment]
Awesome, Ill try to find a few which are beginner friendly and ask others what they would also add.
