### ISSUE TITLE
Print Hello world

### ISSUE THREAD

**Issue by Abhishk9675** [MunGell/awesome-for-beginners#772]
I can change this problem

**Comment by irsayvid** [comment]
should I create a new file and add code or should I do something else. Can you please elaborate I would like to contribute

**Comment by Shyanukant** [comment]
# this program prints Hello, World! in python
print('Hello, World !' )

**Comment by Kingmandeep** [comment]
i can change this problem

**Comment by bingJunior** [comment]
Hello world in Kotlin:

fun main()
{
println("Hello world")
}

**Comment by MousumiDas625** [comment]
_//Hello World in Java__

System.out.println("Hello World!!!")

**Comment by TreavVasu** [comment]
In Dart 
     ` print("Hello world")`

**Comment by Boobiee** [comment]
#In python 
Print("hello world)

**Comment by Dinethri** [comment]
In Java

public static void main(String args[]){
Now Type the System.out.println("Hello World");

**Comment by arupam** [comment]
in bash:

**Comment by emmzzy** [comment]
In Python

Print("hello world")

**Comment by RamadhanIbnu** [comment]
In C++

int main() {
  cout << "Hello World!";
  return 0;
}

**Comment by Harshitbhatt69** [comment]
In Javascript
`console.log("Hello world")`

**Comment by aastha-b** [comment]
This is hello world In Java

public static void main(String args[]){
Now Type the System.out.println("Hello World");

This is hello world in Java Script
console.log("Hello world")

This is hello world in python
print('Hello world')

This is hello world in C++
int main() {
cout << "Hello World!";
return 0;
}

**Comment by Ritika815** [comment]
Print(Hello World)

**Comment by Kingmandeep** [comment]
--> In python
print("Hello World")

-->In c++
#include<iostream>
using namespace std;
int main()
{
cout<<"Hello World";
}

--> In java
package main;

public class Mand {

	public static void main(String[] args) {
		
		
		System.out.println("Hello World");

	}

}

**Comment by prathmesh-Chaudhari05** [comment]
For Python the Basic code is:
`print("Hello World.")`

`print("This is Python 3.6 version.")`

**Comment by aniket173000** [comment]
PRINTING HELLO WORLD IN C WITHOUT USING SEMICOLON :
int  main(){
int e=0;
if(printf("HELLO WORLD ."))
e=1;
}
