### ISSUE TITLE
Cliquet is Deprecated

### ISSUE THREAD

**Issue by NatKarmios** [MunGell/awesome-for-beginners#86]
> Cliquet has been folded into the Kinto package under the new name `kinto.core`. You should update your code to import `kinto.core` instead of `cliquet`, and all `cliquet.*` settings are now prefixed with `kinto` instead. See https://mail.mozilla.org/pipermail/kinto/2016-May/000119.html for more about the background for this decision.

**Comment by MunGell** [comment]
Thank you! Removed from the list
