### ISSUE TITLE
Is it welcome to add projects?

### ISSUE THREAD

**Issue by fennecdjay** [MunGell/awesome-for-beginners#872]
I'm the owner of [this](https://github.com/Gwion) organization, towards the development of a musical programming language. This (small for now) community is very welcoming, and I think our repos would make a nice addition to your list, especially since most of them are in `C` and there is only neovim in this category as of now.

I just added the `first-timers-only` label to all repos, using
```sh
for repo in gwion-plug gwion-sporth gwion-benchmark gwion-cinch-bot gwion-coverage-report Gwion gwion-util gwion-ast gwion-docs gwion-soundpipe gwion-swig
do curl -s -H "Authorization: token $TOKEN" -X POST "https://api.github.com/repos/Gwion/$repo/labels" -d "{\"name\":\"first-timers-only\", \"color\":\"d93f0b\"}"
done
```

**Comment by DurveshKumarPal** [comment]
yes, add project
