### ISSUE TITLE
Rename Docker to Moby

### ISSUE THREAD

**Issue by sahildua2305** [MunGell/awesome-for-beginners#88]
[https://github.com/moby/moby/labels/exp%2Fbeginner](https://github.com/moby/moby/labels/exp%2Fbeginner)

**Comment by MunGell** [comment]
Hi @sahildua2305 

Thank you for raising this issue. I am going to mark it as "beginner-friendly", so a new contributor will be able to pick it.

What needs to be done:

1. Docker to be re-named to Moby in the list
2. Link to the project should be changed to https://github.com/moby/moby/labels/exp%2Fbeginner

Thanks
