### ISSUE TITLE
An unnecessary comma in README.md

### ISSUE THREAD

**Issue by shivanisorte** [MunGell/awesome-for-beginners#897]
[awesome-for-beginners](https://github.com/shivanisorte/awesome-for-beginners.git) _(label: good-first-contribution)_ <br>
Found an unnecessary comma in a compound predicate in the README.md file.

![Screenshot 2020-11-16 221935](https://user-images.githubusercontent.com/69205415/99283288-cf98d700-285a-11eb-876c-75f6abe96767.png)

**Comment by praneeth2022** [comment]
removed unwanted comma in readme #904
