### ISSUE TITLE
Please add mobile technologies too

### ISSUE THREAD

**Issue by SumukhaK** [MunGell/awesome-for-beginners#914]
Android apps using Java, Kotlin, iOS apps, React native there is so much more which can be added to the list. Please look into them. Thanks and Cheers for the effort.

**Comment by a-dera** [comment]
Have you some projects to share with us?
Also, several of the projects don't have a good code of conduct or good documentation. Then, they can't be mentioned here. Remember this list is for beginners.

**Comment by MunGell** [comment]
Hi @SumukhaK 

Feel free to raise PRs for any of the projects you think are worth adding here.
