### ISSUE TITLE
Remove archived repository from the list - Batavia

### ISSUE THREAD

**Issue by abxhr** [MunGell/awesome-for-beginners#976]
While browsing through the Python Projects, I found that the Repository [`Pybee/batavia`](https://github.com/beeware/batavia/labels/first-timers-only) is *Archived* (being a read-only repository). Hence, I don't think it is relevant to index that project here for people looking to contribute.

(*Amazing work with this repository!* 🚀)

**Comment by Satish985** [comment]
I want to work on this project and fix this problem. Please help and guide me.............

**Comment by Satish-Tiwari** [comment]
I want to work on this project and fix this problem. Please help and guide me...............

**Comment by 65r** [comment]
Give me more time

در تاریخ شنبه ۱۸ سپتامبر ۲۰۲۱،‏ ۹:۱۰ ق.ظ Satish Tiwari <
***@***.***> نوشت:

**Comment by priyakumari02** [comment]
I want to work on this issue

**Comment by tamal-kundu** [comment]
i can fix this issue.. can u assign me for resolving this issue? i am a beginner.
