### ISSUE TITLE
Can i add my own proyect?

### ISSUE THREAD

**Issue by MontejoJorge** [MunGell/awesome-for-beginners#982]
I am doing a project and I would like that beginners can contribute to learn from each other, does a project need to be advanced to be included here?

**Comment by 65r** [comment]
Ok can you send me your project pictures

در تاریخ جمعه ۱۷ سپتامبر ۲۰۲۱،‏ ۱۲:۱۴ ب.ظ Jorge Montejo <
***@***.***> نوشت:

**Comment by anishlukk123** [comment]
I dont think it needs to be super advanced
